CREATE TABLE "watchly_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "watchly_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "watchly_movie" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watchly_movie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tmdb_id" integer NOT NULL,
	"type" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watchly_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watchly_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "watchly_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watchly_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp,
	"image" varchar(255),
	"password_hash" varchar(255) NOT NULL,
	"username" varchar(255),
	"first_name" varchar(255),
	"last_name" varchar(255),
	"display_name" varchar(255),
	"profile_picture" varchar(255),
	"bio" varchar(360),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp
);
--> statement-breakpoint
CREATE TABLE "watchly_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "watchly_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "watchly_watchlist" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watchly_watchlist_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" varchar(255) NOT NULL,
	"movie_ids" jsonb[],
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "watchly_watchlist_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watchly_watchlist_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"watchlist_id" integer NOT NULL,
	"movie_id" integer NOT NULL,
	"status" varchar(255) NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "watchly_account" ADD CONSTRAINT "watchly_account_user_id_watchly_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."watchly_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchly_post" ADD CONSTRAINT "watchly_post_created_by_watchly_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."watchly_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchly_session" ADD CONSTRAINT "watchly_session_user_id_watchly_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."watchly_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchly_watchlist" ADD CONSTRAINT "watchly_watchlist_user_id_watchly_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."watchly_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchly_watchlist_item" ADD CONSTRAINT "watchly_watchlist_item_watchlist_id_watchly_watchlist_id_fk" FOREIGN KEY ("watchlist_id") REFERENCES "public"."watchly_watchlist"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "watchly_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "watchly_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "name_idx" ON "watchly_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "watchly_session" USING btree ("user_id");